In [2]:
!pip install datasets

Requirement already satisfied: datasets in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (5.0.0)
Requirement already satisfied: filelock in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (3.31.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (2.3.4)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in C:\Users\gupta\AppData\Roaming\Python\Python313\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (1.24.0)
Requirement already satisfied: packaging in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\gupta\AppData\Roaming\Python\Python313\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in C:\Users\gupta\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1.0.0->datasets) (2025.8.3)
Requirement already satisfied: httpcore==1.* in C:\Users\gupta\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in C:\Users\gupta\AppData\Roaming\Python\Python313\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.2)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.14.1)
Requirement already satisfied: colorama in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.32.2->datasets) (1.26.20)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
from datasets import load_dataset

In [4]:
from datasets import load_dataset
ds = load_dataset("CShorten/ML-ArXiv-Papers",split='train')# Extracts only the training portion of the dataset

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
ds[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd
df = pd.DataFrame(ds)

In [7]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [8]:
df = df[['title','abstract']].head(15000)

In [9]:
df.shape
df.head()

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [10]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [11]:
df['paper_text']= df['title'] +' ' +df['abstract']

In [12]:
df.head()

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...

In [13]:
df[['paper_text']].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [14]:
type(df['paper_text'])

pandas.core.series.Series

In [15]:
print(df['paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [16]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

In [17]:
from sentence_transformers import SentenceTransformer

In [18]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
#data preprocessing is not necessary since the model is already that much trianed to ignore stop words

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [19]:
sample_text = df['paper_text'].iloc[0]

In [20]:
print(sample_text)

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.

In [21]:
#to remove spaces from the front and back side
sample_text = sample_text.strip()

In [22]:
embedding = model.encode(sample_text)
print(embedding)

[-1.31564096e-01 -6.78268867e-03 -3.67610296e-03  3.26515771e-02
  1.12196416e-01  1.22726774e-02  9.81672108e-02 -9.00522918e-02
  4.23116274e-02 -1.97734609e-02 -3.30841988e-02  7.45294765e-02
  1.06320404e-01 -2.06043329e-02 -2.05210466e-02  1.69494213e-03
  7.08195195e-02  5.85445836e-02 -1.12319082e-01  2.08247546e-02
  5.69254495e-02  2.01578029e-02  2.58310866e-02  3.21702994e-02
  1.05137646e-01 -9.67676491e-02  2.70080380e-02 -2.34508999e-02
 -4.54967655e-02 -1.01369740e-02 -1.79485474e-02 -4.81442921e-02
  1.07765412e-02 -3.75907160e-02  1.94348264e-02  3.71518731e-02
  2.96784602e-02  4.33094017e-02  4.37321253e-02  3.70486900e-02
 -1.82591542e-03  4.55186283e-03 -7.99065083e-03  3.03736813e-02
 -1.43780010e-02  3.79514582e-02  5.95915951e-02 -2.58335713e-02
 -6.52157813e-02  5.90026900e-02 -2.10713428e-02  7.35942200e-02
 -5.72010614e-02  2.94057326e-03  7.67515227e-03 -3.33416164e-02
 -2.41654590e-02 -2.09911186e-02 -4.76783998e-02  1.42029986e-01
 -4.16862927e-02 -2.28165481e-02 -1.45359123e-02 -4.39256057e-03
 -6.80174604e-02 -2.55160825e-03  7.34625012e-02  4.29371707e-02
 -3.04794312e-02  5.82109392e-02 -8.45503956e-02 -5.60204638e-03
 -9.26086158e-02  5.90392239e-02  1.99682117e-02 -1.46549540e-02
  8.56686160e-02  3.43409777e-02  4.26302897e-03 -2.55769137e-02
 -2.92939022e-02  2.88602710e-03  3.02557983e-02 -5.09372950e-02
  3.13304141e-02 -1.24026500e-02  1.93743147e-02  7.15281814e-02
  3.50777991e-02  4.40819561e-03 -1.08218893e-01 -2.98318118e-02
 -6.13419786e-02  4.19661961e-02  4.72576991e-02 -5.66610806e-02
  6.82019815e-02 -7.44092390e-02  9.27868187e-02  9.60959420e-02
 -6.80272579e-02  1.62349513e-03  4.31859158e-02 -3.07624061e-02
  1.11809252e-02 -8.54723975e-02  2.37832703e-02  1.73624661e-02
  5.39867720e-03  1.58847068e-02  4.44360636e-03 -1.15580987e-02
 -9.76493210e-03 -7.40202516e-03 -1.88762322e-02 -3.39675583e-02
 -4.86566573e-02  4.36526909e-02 -1.04922533e-01 -8.63315165e-02
 -4.52508144e-02 -7.29720518e-02 -2.08166353e-02  3.65954041e-02
 -8.82895291e-03 -2.35993657e-02 -4.47208323e-02  1.54469288e-33
  2.61055958e-02  5.34729399e-02 -3.32894512e-02 -4.06732596e-02
  2.65870821e-02  8.22318643e-02 -7.54068140e-03 -1.62822413e-04
  6.65080175e-02  4.61811721e-02 -4.74174134e-02 -5.05928099e-02
 -3.38295251e-02  4.62175831e-02  4.43544984e-02  4.41354886e-02
 -7.10298717e-02  7.09743202e-02  1.83767769e-02 -7.27372691e-02
  7.00071007e-02 -2.09408011e-02 -5.53729124e-02 -4.75663356e-02
 -4.31162231e-02 -5.32935932e-02  2.69040262e-04 -3.83734256e-02
  1.12205092e-02  1.13959191e-02 -5.69416247e-02 -3.37938033e-03
  1.03546843e-01 -8.47087055e-02  3.53649026e-03 -5.72200939e-02
  1.27505269e-02 -5.53163560e-03 -8.56065601e-02  3.96663994e-02
  2.25463789e-02  4.99202088e-02  4.13551331e-02 -2.60567442e-02
 -5.83662577e-02 -7.51372203e-02  1.08070455e-01  6.15566445e-04
 -9.01390985e-02 -1.32652521e-01 -2.54444731e-03 -3.37498039e-02
 -9.57633108e-02  2.57460604e-04  1.16859209e-02  2.23589931e-02
  4.88692448e-02 -4.24660556e-02 -2.45967209e-02  8.56855512e-02
 -8.03445280e-02  3.33040766e-02  5.40195405e-02 -3.71835902e-02
  2.11837629e-04  1.86595991e-02  3.10018547e-02 -5.36220409e-02
  5.17720357e-02 -1.01843230e-01  3.34465019e-02 -4.58092615e-03
 -2.21983027e-02 -5.00103012e-02  3.52233276e-02  1.97152440e-02
  1.44825177e-02 -6.63907500e-03 -1.26853166e-02 -1.63108564e-03
 -4.83979359e-02 -4.59996164e-02 -1.93057749e-02 -2.97057424e-02
 -5.00632413e-02  3.04492842e-02  1.81869436e-02 -4.53428328e-02
 -4.88783941e-02  1.22219627e-03 -1.06096029e-01 -3.71801220e-02
 -7.55688101e-02 -4.81151417e-02  2.25064084e-02 -2.23424485e-33
 -2.21984070e-02  8.51171166e-02  2.62743980e-02  5.43513559e-02
 -1.57290399e-02 -1.96614917e-02 -2.73119994e-02  2.96456609e-02
 -4.53337422e-03 -8.33164006e-02 -9.22681764e-02 -4.08938043e-02
  7.32074380e-02  4.30881567e-02 -7.74768889e-02  7.20389709e-02
 -1.40663190e-02  4.46009710e-02 -4.19447720e-02  3.33845131e-02
  2.91045867e-02  3.20830345e-02  2.09529269e-02  2.23059654e-02
  4.44135517e-02  2.03914512e-02 -5.60238101e-02  1.84909642e-01
  2.28254460e-02 -7.39140529e-03 -4.18754481e-02 -7.15966821e-02
 -6.42080829e-02 -6.63447380e-02 -2.05955282e-02  1.06428834e-02
  5.02155116e-03  6.77871034e-02 -7.12078661e-02  1.02496631e-01
  9.44258943e-02  3.30481716e-02 -5.00413515e-02  2.62115244e-02
  5.58213852e-02 -6.59461915e-02  1.79097056e-02 -1.04769953e-02
  7.34620616e-02 -2.46883580e-03  3.85357663e-02  4.46167439e-02
 -2.85523348e-02  9.08054858e-02 -7.84088485e-03 -2.77603231e-03
 -9.57009718e-02 -1.16200252e-02  5.25497347e-02  9.29363668e-02
 -6.14791876e-03  8.09931103e-03 -6.72860518e-02  8.18503276e-02
  3.28590581e-03 -3.50581110e-02 -1.84767246e-02 -8.98427170e-05
  7.32783228e-02  9.57325771e-02  4.15685959e-02 -6.18869327e-02
  2.83940211e-02  4.25410084e-02  1.89858414e-02  1.06751146e-02
  2.51713824e-02  3.08218561e-02 -6.59718737e-02  8.87987316e-02
  3.82416919e-02  9.21778977e-02  5.19545227e-02  2.64025433e-03
  1.49981398e-03  5.44707105e-02  7.31122121e-02 -8.08786310e-04
  7.52013847e-02 -1.16245195e-01  1.17986761e-02  6.28149360e-02
 -3.60431001e-02  2.93700527e-02 -1.52511969e-02 -4.79335256e-08
 -5.37610501e-02 -2.84531619e-02  2.40290053e-02 -7.81880766e-02
  1.01736069e-01 -2.52304301e-02  7.01656472e-03 -2.86815804e-03
  2.01843623e-02 -3.77830602e-02  7.34866336e-02 -1.10321329e-03
 -7.07775876e-02 -4.50034998e-02 -2.81599369e-02  1.05185444e-02
 -3.94661073e-03  3.17635126e-02  2.70489398e-02  2.42667291e-02
  3.24969031e-02 -2.10961532e-02 -5.78849437e-03 -2.25947537e-02
  2.25187950e-02 -6.81575611e-02  3.87890115e-02 -2.75328737e-02
  1.55410618e-02  1.14076264e-01 -5.39854951e-02  3.54755335e-02
  7.14311972e-02 -5.83239608e-02  4.58904309e-03  1.56194698e-02
  1.03841359e-02 -4.26567793e-02  1.35176852e-02 -5.60860336e-02
  1.86445713e-02 -1.47688473e-02 -4.86133918e-02 -1.01973712e-02
  6.46221265e-02  1.17162503e-02  4.91274521e-02 -4.35938537e-02
 -2.97330115e-02 -5.42693026e-02  3.84951904e-02  1.90192852e-02
  6.83268160e-02 -4.08833362e-02  4.66428138e-02  3.03019118e-03
 -1.16352011e-02 -5.24238236e-02 -3.03320885e-02  2.34114844e-02
  2.92673800e-03  9.56124738e-02 -4.42394316e-02  5.22624049e-03]

In [23]:
embedding.shape

(384,)

# To prove that embedding is formed correctly by considering top 5 values of embeddings and finding there cosine similarity

In [24]:
sample_embedding = model.encode(df['paper_text'].head(5).to_list())

In [25]:
sample_embedding.shape

(5, 384)

In [26]:
type(sample_embedding)

numpy.ndarray

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarity = cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))

In [29]:
print(similarity)

[[1.0000001]]

In [30]:
for i in range (1,5):
  sim = cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[0.36625272]]
[[0.33522844]]
[[0.1550511]]
[[0.37421542]]

In [45]:
#creating embeddings using sentence transformer model
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
  print("Loading saved embeddings file in loaded_emb")
  loaded_emb = np.load('paper_embeddings.npy')
else:
  print("Generating embeddings")
  embeddings = model.encode(df["paper_text"].to_list(), batch_size = 32, show_progress_bar = True)
  np.save('paper_embeddings.npy', embeddings)

Loading saved embeddings file in loaded_emb

In [48]:
!pip install faiss-cpu
import faiss

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp313-cp313-win_amd64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from faiss-cpu) (2.3.4)
Requirement already satisfied: packaging in C:\Users\gupta\AppData\Local\Programs\Python\Python313\Lib\site-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.14.3-cp313-cp313-win_amd64.whl (16.2 MB)
   ---------------------------------------- 0.0/16.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.2 MB 5.7 MB/s eta 0:00:03
   --- ------------------------------------ 1.6/16.2 MB 6.1 MB/s eta 0:00:03
   ------- -------------------------------- 3.1/16.2 MB 6.2 MB/s eta 0:00:03
   ----------- ---------------------------- 4.5/16.2 MB 6.2 MB/s eta 0:00:02
   -------------- ------------------------- 6.0/16.2 MB 6.5 MB/s eta 0:00:02
   ------------------ --------------------- 7.6/16.2 MB 6.6 MB/s eta 0:00:02
   ---------------------- ----------------- 8.9/16.2 MB 6.6 MB/s eta 0:00:02
   ------------------------- -------------- 10.5/16.2 MB 6.7 MB/s eta 0:00:01
   ----------------------------- ---------- 12.1/16.2 MB 6.7 MB/s eta 0:00:01
   ------------------------------- -------- 12.8/16.2 MB 6.2 MB/s eta 0:00:01
   --------------------------------- ------ 13.6/16.2 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.2/16.2 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 16.2/16.2 MB 6.0 MB/s  0:00:02
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [ ]:
loaded_emb.shape

(1, 384)

In [66]:
#normalizing embeddings to use for faiss
faiss.normalize_L2(loaded_emb)
loaded_emb.shape

(1, 384)

In [72]:
#creating index on the dimensionality of each vector embedding
import os
import numpy as np
import faiss
if os.path.exists("faiss_index.npy"):
    print("loading the saved index file")
    index = faiss.read_index('faiss_index.npy')
else:
    print("Generating the index file")
    index = faiss.IndexFlatIP(loaded_emb.shape[1])
    index.add(loaded_emb)
    faiss.write_index(index,'faiss_index.npy')

loading the saved index file

In [52]:
query = ['Transformers in Deep Learning and its self attention mechanism']
query_emb = model.encode(query)
type(query_emb)
query_emb.shape

(1, 384)

In [53]:
# Normalizing query embeddings
faiss.normalize_L2(query_emb)
type(query_emb)

numpy.ndarray

In [ ]:
#performing search via faiss(which uses cosine similarity)
D,I = index.search(query_emb,5)
D,I

In [ ]:
df.iloc[115389]['title']
df['paper_text'].iloc[115389]

## Main Function to Generate similarity score##

In [ ]:
# Creating a general function for finding similarity score of list of queries
def get_similarity_score (query,k=5):
    query_embed = model.encode(query)
    faiss.normalize_L2(query_embed)
    D,I = index.search(query_embed,k)
    return D,I

In [79]:
get_similarity_score(query,6)

(array([[ 1.0190096e-02, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
         -3.4028235e+38, -3.4028235e+38]], dtype=float32),
 array([[ 0, -1, -1, -1, -1, -1]]))